apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: my-app
  strategy: 
    # type: Recreate
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: gcr.io/gdgkl-438603/my-app:v2
        # env:
        # - name: DB_USERNAME
        #   valueFrom:
        #     configMapKeyRef:
        #       name: db-config
        #       key: DB_USERNAME
        # - name: DB_PASSWORD
        #   valueFrom:
        #     configMapKeyRef:
        #       name: db-config
        #       key: DB_PASSWORD
        # - name: DB_NAME
        #   valueFrom:
        #     configMapKeyRef:
        #       name: db-config
        #       key: DB_NAME
        # - name: DB_HOST
        #   valueFrom:
        #     configMapKeyRef:
        #       name: db-config
        #       key: DB_HOST
        # - name: DB_PORT
        #   valueFrom:
        #     configMapKeyRef:
        #       name: db-config
        #       key: DB_PORT
        ports:
        - containerPort: 8080

