apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast-sssd
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd  # Use SSD storage
  replication-type: none
allowVolumeExpansion: true  # Allow resizing the volume
reclaimPolicy: Retain  # Volume will not be deleted when PVC is deleted
