# Stage 1: Build the Go binary
FROM golang:1.23-alpine AS builder


WORKDIR /app
COPY . .
RUN go build -o go-app .

# Stage 2: Create a lightweight container
FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/. .
EXPOSE 8080
CMD ["./go-app"]
