apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-app
  name: my-app
  namespace: default
spec:
  replicas: 4
  selector:
    matchLabels:
      app: my-app
  strategy: 
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - image: gcr.io/gdgkl-438603/my-app:v1
        name: my-app
        ports:
          - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"   # Minimum memory the container needs
            cpu: "100m"       # Minimum CPU the container needs
          limits:
            memory: "512Mi"   # Maximum memory to use
            cpu: "500m"          # Maximum CPU to use
